import { describe, expect, it } from "bun:test";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const REPO_ROOT = path.resolve(__dirname, "..");
const TMP = path.join(REPO_ROOT, "tmp", "graph-test");

function run(args: string[]): string {
  return execFileSync(
    "node",
    ["--experimental-strip-types", "scripts/generate-skills-graph.ts", ...args, "--root", REPO_ROOT],
    {
      encoding: "utf-8",
      cwd: REPO_ROOT,
      env: {
        PATH: process.env.PATH ?? "",
        HOME: process.env.HOME ?? "",
        TMPDIR: process.env.TMPDIR ?? "",
        LANG: process.env.LANG ?? "",
      },
    }
  );
}

describe("generate-skills-graph", () => {
  it("emits a JSON adjacency map with valid edges", () => {
    fs.mkdirSync(TMP, { recursive: true });
    const jsonPath = path.join(TMP, "graph.json");
    const out = run(["--json", jsonPath]);
    expect(out).toContain("wrote graph");

    const json = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
    expect(json.version).toBe(1);
    expect(json.count).toBeGreaterThan(0);
    const names = new Set<string>(json.skills.map((s: { name: string }) => s.name));
    expect(names.size).toBe(json.count);
    for (const edge of json.edges as Array<{ from: string; to: string }>) {
      expect(names.has(edge.from)).toBe(true);
      expect(names.has(edge.to)).toBe(true);
    }
    for (const skill of json.skills as Array<{ name: string; usedBy: string[]; dependsOn: string[] }>) {
      for (const u of skill.usedBy) expect(names.has(u)).toBe(true);
      for (const d of skill.dependsOn) expect(names.has(d)).toBe(true);
    }
  });

  it("emits per-skill Mermaid markdown plus index.md (no d2/svg)", () => {
    const dir = path.join(TMP, "graphs");
    const out = run(["--graph-dir", dir]);
    expect(out).toContain("per-skill graphs");

    const indexPath = path.join(dir, "index.md");
    expect(fs.existsSync(indexPath)).toBe(true);
    const index = fs.readFileSync(indexPath, "utf-8");
    expect(index).toContain("# Skills dependency graphs");
    expect(index).toMatch(/\| Skill \| Dependencies \| Dependents \| Graph \|/);
    expect(index).toContain("<!-- AUTO-GENERATED");
    expect(index).toContain("⚠️ **AUTO-GENERATED — do not edit this file by hand.**");
    expect(index).toContain("`npm run graph:update`");

    const files = fs.readdirSync(dir);
    expect(files.some((f) => f.endsWith(".d2"))).toBe(false);
    expect(files.some((f) => f.endsWith(".svg"))).toBe(false);
    expect(files.filter((f) => f.endsWith(".md")).length).toBeGreaterThan(0);

    const jsonPath = path.join(TMP, "graph2.json");
    run(["--json", jsonPath]);
    const j = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
    const sample = (j.skills as Array<{ name: string }>).slice(0, 3);
    for (const skill of sample) {
      const md = fs.readFileSync(path.join(dir, `${skill.name}.md`), "utf-8");
      expect(md).toContain(`# ${skill.name}`);
      expect(md).toContain("```mermaid");
      expect(md).toContain("graph LR");
      expect(md).toContain("<!-- AUTO-GENERATED");
      expect(md).toContain("⚠️ **AUTO-GENERATED — do not edit this file by hand.**");
      expect(md).toContain("`npm run graph:update`");
      expect(md).not.toContain(".d2");
      expect(md).not.toContain(".svg");
    }
  });

  it("truncates when a skill has more neighbors than the cap", () => {
    const dir = path.join(TMP, "graphs-tight");
    run(["--graph-dir", dir, "--neighbors", "2"]);
    const jsonPath = path.join(TMP, "graph-tight.json");
    run(["--json", jsonPath, "--neighbors", "2"]);
    const json = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
    const hub = (json.skills as Array<{ name: string; dependsOn: string[]; usedBy: string[] }>)
      .slice()
      .sort((a, b) => (b.dependsOn.length + b.usedBy.length) - (a.dependsOn.length + a.usedBy.length))[0];
    if (hub.dependsOn.length > 2 || hub.usedBy.length > 2) {
      const md = fs.readFileSync(path.join(dir, `${hub.name}.md`), "utf-8");
      expect(md).toContain("truncated");
    }
  });

  it("supports --neighbors=1", () => {
    const dir = path.join(TMP, "graphs-1");
    run(["--graph-dir", dir, "--neighbors", "1"]);
    const files = fs.readdirSync(dir).filter((f) => f.endsWith(".md") && f !== "index.md");
    expect(files.length).toBeGreaterThan(0);
    const one = fs.readFileSync(path.join(dir, files[0]), "utf-8");
    expect(one).toMatch(/```mermaid[\s\S]+graph LR/);
  });

  it("removes stale .md files from previous runs", () => {
    const dir = path.join(TMP, "graphs-stale");
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, "deleted-skill.md"), "# orphan\n", "utf-8");
    fs.writeFileSync(path.join(dir, "another-orphan.md"), "# orphan\n", "utf-8");
    run(["--graph-dir", dir]);
    const remaining = new Set(
      fs.readdirSync(dir).filter((f) => f.endsWith(".md"))
    );
    expect(remaining.has("deleted-skill.md")).toBe(false);
    expect(remaining.has("another-orphan.md")).toBe(false);
    expect(remaining.has("index.md")).toBe(true);
  });

  it("keeps the unknown-refs count out of the rendered skill stats", () => {
    const dir = path.join(TMP, "graphs-uk");
    run(["--graph-dir", dir, "--allow-unknown-refs"]);
    const skill = fs
      .readdirSync(dir)
      .filter((f) => f.endsWith(".md") && f !== "index.md")
      .map((f) => fs.readFileSync(path.join(dir, f), "utf-8"))
      .find((c) => /## Stats[\s\S]+\d+ dependencies/.test(c));
    expect(skill).toBeDefined();
    const m = skill!.match(/(\d+) dependencies/);
    expect(m).not.toBeNull();
    const count = Number(m![1]);
    const mermaidMatch = skill!.match(/```mermaid[\s\S]+?```/);
    expect(mermaidMatch).not.toBeNull();
    const mermaidEdges = (mermaidMatch![0].match(/-->/g) || []).length;
    expect(count).toBeLessThanOrEqual(mermaidEdges);
  });
});