#!/usr/bin/env bash
# Collect reserved names from per-agent YAML files and generate reserved-names.sh.
#
# Usage: collect-reserved.sh [OUTPUT_FILE]
#   OUTPUT_FILE  defaults to scripts/reserved-names.sh (project root)
#
# Reads: skills/tools/skillmaker/assets/agents/*.yaml
# Writes: reserved-names.sh (bash sourceable, with RESERVED_NAMES array + RESERVED_SET)
#
# Requires: node (uses only stdlib, no external packages)
set -euo pipefail

REPO_ROOT=$(cd "$(dirname "$0")/../../../.." && pwd -P)
AGENTS_DIR="${REPO_ROOT}/skills/tools/skillmaker/assets/agents"
OUTPUT="${1:-${REPO_ROOT}/scripts/reserved-names.sh}"

# Use Node to parse the simple YAML lists (no external deps needed).
ALL_COMMANDS=$(node - "$AGENTS_DIR" <<'NODEEOF'
const fs = require('fs');
const path = require('path');
const agentsDir = process.argv[2];
const commands = new Set();
const yamls = fs.readdirSync(agentsDir)
  .filter((f) => f.endsWith('.yaml'))
  .sort();
for (const yaml of yamls) {
  const content = fs.readFileSync(path.join(agentsDir, yaml), 'utf8');
  const lines = content.split(/\r?\n/);
  let inCommands = false;
  for (const raw of lines) {
    const line = raw.trim();
    if (line.startsWith('commands:')) {
      inCommands = true;
      continue;
    }
    if (inCommands) {
      const m = line.match(/^-\s*(.+)$/);
      if (m) {
        const cmd = m[1].trim().replace(/^["']|["']$/g, '').replace(/^\//, '');
        if (cmd) {
          commands.add(cmd);
        }
      } else {
        inCommands = false;
      }
    }
  }
}
const sorted = [...commands]
  .sort()
  .filter((cmd) => /^[a-z0-9]+(-[a-z0-9]+)*$/.test(cmd));
console.log(sorted.join('\n'));
NODEEOF
)

# Read into array.
mapfile -t SORTED <<< "$ALL_COMMANDS"

# Format into 80-char-wide columns.
Lines=()
Line=""
for cmd in "${SORTED[@]}"; do
  cmd=$(echo "$cmd" | tr -d '[:space:]')
  [[ -z "$cmd" ]] && continue
  if [[ ${#Line} -eq 0 ]]; then
    Line="  $cmd"
  elif [[ $(( ${#Line} + ${#cmd} + 2 )) -lt 78 ]]; then
    Line="$Line  $cmd"
  else
    Lines+=("$Line")
    Line="  $cmd"
  fi
done
[[ -n "$Line" ]] && Lines+=("$Line")

# Write the generated file.
cat > "$OUTPUT" << HEADER
# shellcheck shell=bash
# AUTO-GENERATED by collect-reserved.sh — do not edit manually.
# Source: skills/tools/skillmaker/assets/agents/*.yaml
# Regenerate: ./skills/tools/skillmaker/scripts/collect-reserved.sh

RESERVED_NAMES=(
$(printf '%s\n' "${Lines[@]}")
)

# shellcheck disable=SC2034
declare -A RESERVED_SET
# shellcheck disable=SC2034
for r in "\${RESERVED_NAMES[@]}"; do RESERVED_SET["\$r"]=1; done
HEADER

echo "Generated ${OUTPUT} ($(echo "$ALL_COMMANDS" | grep -c .) unique names from ${AGENTS_DIR}/*.yaml)"
