#!/usr/bin/env bash
# Collect reserved names from per-agent YAML files and generate reserved-names.sh.
#
# Usage: collect-reserved.sh [OUTPUT_FILE]
#   OUTPUT_FILE  defaults to scripts/reserved-names.sh (project root)
#
# Reads: skills/tools/skillmaker/assets/agents/*.yaml
# Writes: reserved-names.sh (bash sourceable, with RESERVED_NAMES array + RESERVED_SET)
#
# Requires: python3 (uses only stdlib, no PyYAML)
set -euo pipefail

REPO_ROOT=$(cd "$(dirname "$0")/../../../.." && pwd -P)
AGENTS_DIR="${REPO_ROOT}/skills/tools/skillmaker/assets/agents"
OUTPUT="${1:-${REPO_ROOT}/scripts/reserved-names.sh}"

# Use Python to parse the simple YAML lists (no external deps needed).
ALL_COMMANDS=$(python3 - "$AGENTS_DIR" << 'PYEOF'
import sys, glob, re

agents_dir = sys.argv[1]
commands = set()

for path in sorted(glob.glob(f"{agents_dir}/*.yaml")):
    with open(path) as f:
        in_commands = False
        for line in f:
            stripped = line.strip()
            if stripped.startswith("commands:"):
                in_commands = True
                continue
            if in_commands:
                m = re.match(r"^\s*-\s*(.+)$", stripped)
                if m:
                    cmd = m.group(1).strip().strip('"').strip("'")
                    if cmd:
                        commands.add(cmd.lstrip("/"))
                else:
                    in_commands = False

for cmd in sorted(commands):
    # Only include kebab-case names (matching skill naming rules).
    if re.match(r'^[a-z0-9]+(-[a-z0-9]+)*$', cmd):
        print(cmd)
PYEOF
)

# Read into array.
mapfile -t SORTED <<< "$ALL_COMMANDS"

# Format into 80-char-wide columns.
Lines=()
Line=""
for cmd in "${SORTED[@]}"; do
  cmd=$(echo "$cmd" | tr -d '[:space:]')
  [[ -z "$cmd" ]] && continue
  if [[ ${#Line} -eq 0 ]]; then
    Line="  $cmd"
  elif [[ $(( ${#Line} + ${#cmd} + 2 )) -lt 78 ]]; then
    Line="$Line  $cmd"
  else
    Lines+=("$Line")
    Line="  $cmd"
  fi
done
[[ -n "$Line" ]] && Lines+=("$Line")

# Write the generated file.
cat > "$OUTPUT" << HEADER
# shellcheck shell=bash
# AUTO-GENERATED by collect-reserved.sh — do not edit manually.
# Source: skills/tools/skillmaker/assets/agents/*.yaml
# Regenerate: ./skills/tools/skillmaker/scripts/collect-reserved.sh

RESERVED_NAMES=(
$(printf '%s\n' "${Lines[@]}")
)

# shellcheck disable=SC2034
declare -A RESERVED_SET
# shellcheck disable=SC2034
for r in "\${RESERVED_NAMES[@]}"; do RESERVED_SET["\$r"]=1; done
HEADER

echo "Generated ${OUTPUT} ($(echo "$ALL_COMMANDS" | grep -c .) unique names from ${AGENTS_DIR}/*.yaml)"
